version: '2.4'

services:
  offerwall-nginx:
    container_name: offerwall-nginx
    build: ./docker/nginx
    hostname: offerwall-nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/app
      - ./docker/nginx/config/app-prod.conf:/etc/nginx/conf.d/app.conf
      - /data/docker/offerwalls/nginx/logs:/var/log/nginx
      - /etc/letsencrypt:/etc/letsencrypt
      - ./docker/nginx/letsencrypt/cli.ini:/etc/letsencrypt/cli.ini
    networks:
      - offerwall-network
    restart: always
    ulimits:
      nofile:
        soft: 128000
        hard: 128000

networks:
  offerwall-network:
    external: true
